### ISSUE TITLE
Not released on npm?

### ISSUE THREAD

**Issue by goloroden** [depcheck/grunt-depcheck#1]
If I try to install this module via npm, I can an error telling me:

> 'grunt-depcheck' is not in the npm registry.

Also, if I try to directly access https://www.npmjs.com/package/grunt-depcheck, I get a `404`. Did you release it to npm?

If not, could you please do it?

**Comment by rumpl** [comment]
Hey, I just published it on npm.

Would you be my alpha tester ? :)

Thanks!

**Comment by goloroden** [comment]
Thanks, man :-)

I'm currently trying to get it to run, but somehow it doesn't complain about anything, no matter what I do.

Can you please elaborate a little bit on the

```
your_target: {
  // Target-specific file lists and/or options go here.
}
```

block? Is it mandatory? Optional? What are "target-specific file lists and/or options"? Any examples?

**Comment by rumpl** [comment]
Could you try with something like this:

``` javascript
depcheck: {
        options: {
            ignoreMatches: ['grunt-*']
        },
        files: {
          'src': ['.app/']
        }
    }
```

I'll update the readme file tomorrow

**Comment by goloroden** [comment]
I'm now using

```
options: {
  ignoreMatches: [ 'foo' ],
  files: {
    src: [ '.' ]
  }
}
```

but nothing happens. If I run `depcheck` as CLI, I get lots of unused dependencies and dev dependencies.

PS: I have also tried setting `src` to the absolute path of the project, again same result, aka nothing ;-)

**Comment by rumpl** [comment]
Try putting files outside of the options.
Like this : 

<pre>
options: {
  ignoreMatches: [ 'foo' ]
},
files: {
    src: [ '.' ]
  }
}
</pre>

**Comment by goloroden** [comment]
Okay, now it works :-)

Thanks for your help!

I've got two other issues, but I will open separate issues for them.

**Comment by rumpl** [comment]
Awesome, thanks man! :)

**Comment by goloroden** [comment]
You're welcome, and thanks for the great work :-)
