### ISSUE TITLE
Explain in documentation what the path '.' means

### ISSUE THREAD

**Issue by goloroden** [depcheck/grunt-depcheck#4]
In #1 you wrote that I might try:

```
files: {
  src: [ '.' ]
}
```

What exactly does `.` refer to? The folder where the Gruntfile is located? The current working directory? …?

**Comment by lijunle** [comment]
Hi, @goloroden I saw you have an old issue. Is this still an issue for you? Maybe you want to contribute to grunt-depcehck project too? 😺

**Comment by goloroden** [comment]
Haha 😂 

We switched from Grunt to Gulp at least a year ago, so meanwhile, I'm more interested in [gulp-depcheck](https://github.com/mcasimir/gulp-depcheck)

**Comment by lijunle** [comment]
OK, I am closing this one.

I contacted the author of that project but without any reply yet. He has another awesome project - [depcheck-ci](https://github.com/mcasimir/depcheck-ci). 👍

**Comment by goloroden** [comment]
Yes, unfortunately the responsiveness is not that great :-/
