### ISSUE TITLE
withoutDev parameter is initialized incorrectly

### ISSUE THREAD

**Issue by goloroden** [depcheck/grunt-depcheck#5]
See [this line](https://github.com/rumpl/grunt-depcheck/blob/d24a946f9035710713d98ba089167ee6711ef33a/tasks/depcheck.js#L18) and compare it to [what the documentation says](https://github.com/rumpl/grunt-depcheck#optionswithoutdev).

`true` vs `false` ;-)

**Comment by rumpl** [comment]
Corrected, thanks :)

**Comment by goloroden** [comment]
You're welcome :-)
